packages:
  # Core packages
  - 'packages/*'

  # Claude agent core
  - 'claude-agent/*'

  # Applications
  - 'apps/*'

  # Tools
  - 'tools/*'

# Package catalog for consistent dependency management
catalog:
  # Core dependencies
  '@types/node': '^20.11.17'
  typescript: '^5.3.3'
  tsx: '^4.7.1'
  tsc-alias: '^1.8.8'

  # Development tools
  jest: '^29.7.0'
  '@types/jest': '^29.5.12'
  ts-jest: '^29.1.2'
  eslint: '^8.56.0'
  '@typescript-eslint/eslint-plugin': '^6.21.0'
  '@typescript-eslint/parser': '^6.21.0'
  prettier: '^3.1.0'

  # Backend dependencies
  '@nestjs/common': '^10.3.7'
  '@nestjs/core': '^10.3.7'
  '@nestjs/platform-express': '^10.3.7'
  '@nestjs/config': '^3.2.0'
  '@nestjs/swagger': '^7.3.1'
  '@nestjs/jwt': '^10.2.0'
  '@nestjs/passport': '^10.0.3'
  '@nestjs/throttler': '^5.1.2'
  '@nestjs/schedule': '^4.0.0'

  # Database
  '@prisma/client': '^5.9.1'
  prisma: '^5.9.1'

  # AI dependencies
  openai: '^4.26.0'
  anthropic: '^0.15.0'
  langchain: '^0.1.12'
